// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_HA93fFhUR2yY2feAGdLu7QWa368s2rA',
    appId: '1:1039711917059:android:e29a95145c10b15853aa36',
    messagingSenderId: '1039711917059',
    projectId: 'laxxy-9dc6d',
    storageBucket: 'laxxy-9dc6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVnesjmti3_LBQooa4vQcCZ2NuuHL4c5I',
    appId: '1:1039711917059:ios:d39fb2100003643b53aa36',
    messagingSenderId: '1039711917059',
    projectId: 'laxxy-9dc6d',
    storageBucket: 'laxxy-9dc6d.firebasestorage.app',
    androidClientId: '1039711917059-b1rcqss7grsmj7brmvlq1qb55fv8it8p.apps.googleusercontent.com',
    iosClientId: '1039711917059-tquhs6ikoptjm16mjv0uj2uefp3ij0a8.apps.googleusercontent.com',
    iosBundleId: 'com.lexxy.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPI0urV7zkiF1Y7DMANcQnGhHgpyg1DoI',
    appId: '1:1039711917059:web:75c0909d9368234553aa36',
    messagingSenderId: '1039711917059',
    projectId: 'laxxy-9dc6d',
    authDomain: 'laxxy-9dc6d.firebaseapp.com',
    storageBucket: 'laxxy-9dc6d.firebasestorage.app',
    measurementId: 'G-H83DHMEERR',
  );

}