// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq2Tkv0tAmoTZVxAzicXhRLGbqZAiwYkY',
    appId: '1:770931576990:android:a6137d2102ba1dfdc8eb8f',
    messagingSenderId: '770931576990',
    projectId: 'sels-demo',
    storageBucket: 'sels-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQoWDAMTW_HTyN3tEqe8ASPZ_j-sZoohI',
    appId: '1:770931576990:ios:837d739e2235e692c8eb8f',
    messagingSenderId: '770931576990',
    projectId: 'sels-demo',
    storageBucket: 'sels-demo.firebasestorage.app',
    iosBundleId: 'com.lexxy.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPI0urV7zkiF1Y7DMANcQnGhHgpyg1DoI',
    appId: '1:1039711917059:web:75c0909d9368234553aa36',
    messagingSenderId: '1039711917059',
    projectId: 'laxxy-9dc6d',
    authDomain: 'laxxy-9dc6d.firebaseapp.com',
    storageBucket: 'laxxy-9dc6d.firebasestorage.app',
    measurementId: 'G-H83DHMEERR',
  );

}